### ISSUE TITLE
Quick Menu: new design?

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange-canvas-core#16]
Am I the only one who doesn't like the new quick menu design? Are these dark buttons intentional?

<img width="276" alt="Screen Shot 2019-08-12 at 09 40 58" src="https://user-images.githubusercontent.com/12524972/62851155-849e2480-bce5-11e9-9c33-324a1c2d01e8.png">

**Comment by PrimozGodec** [comment]
I like that icons have colors in the background now but I do not like the gradient that icons on the right side have. Why this is not just a single color intensity? I think it would be nicer.

I also do not like the darkness of unselected buttons.

**Comment by irgolic** [comment]
@ajdapretnar 
Toning down the unselected button darkness, refining the shadows to emphasize a tab-like look, how's this?
<img width="296" alt="Screenshot 2019-08-13 at 08 19 28" src="https://user-images.githubusercontent.com/24586651/62919702-c68da000-bda3-11e9-849e-dcdadd3c08e0.png">

@PrimozGodec 
This is what that single color intensity looks like, should the category color be used (which looks nice because it connects with the currently selected tab). Icons aren't as visible on a darker opaque background.
<img width="294" alt="Screenshot 2019-08-13 at 08 26 19" src="https://user-images.githubusercontent.com/24586651/62919819-1b311b00-bda4-11e9-8805-bfd472bec08e.png">

I especially like how the inner glow looks on a list of widgets of different categories.
<img width="292" alt="Screenshot 2019-08-13 at 08 20 22" src="https://user-images.githubusercontent.com/24586651/62919726-d86f4300-bda3-11e9-9f2b-8347cb648a92.png">

**Comment by ajdapretnar** [comment]
I guess it's better than before. I am just a fan of flat icons, just like they were before, but if everyone else is ok with this, then fine.
