### ISSUE TITLE
Quick Menu takes seconds to load when it's first opened

### ISSUE THREAD

**Issue by irgolic** [biolab/orange-canvas-core#7]
##### System specs
Orange canvas version: 0.1.3.dev0
Orange version: 3.23.0.dev
PyQt version: 5.9.2
Operating system: macOS Mojave 10.14.3

##### Expected behavior
Quick Menu loads instantly upon right-click on canvas (also when loading for the first time).

##### Actual behavior
When the quick menu is loaded for the first time, it takes about 2-3 seconds. Afterward, it opens instantly.

##### Steps to reproduce the behavior
I've found that commenting out `orangecanvas/gui/tooltree.py:48` (`view.setUniformRowHeights(True)`) fixes the issue on my computer, even though this is meant to optimize. Perhaps a Qt bug on specific platforms?

**Comment by markotoplak** [comment]
I've seen it happen for a while. I've seen it on Windows mostly, but I though it is connected with slow disks, but never investigated it.

**Comment by ales-erjavec** [comment]
I observe no significant delay on right click alone.
I do see a delay when dragging a new link from an existing node. The cause is the node filter function which causes imports of input/output types to determine allowed nodes (this includes [tsne](https://github.com/biolab/orange3/issues/3523)).

 I see no behavior change with `view.setUniformRowHeights(True)` commented out

**Comment by irgolic** [comment]
This does not happen to me anymore, with or without setting uniform row heights.
