### ISSUE TITLE
Pickling error

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange-canvas-core#91]
Pickling error continuously pops us.

To reproduce:
File (iris) - Box Plot. Click on the big blue field (first to third quartile). Delete File widget.

Stack trace:
```
Traceback (most recent call last):
  File "/Users/ajda/orange/orange-canvas-core/orangecanvas/application/canvasmain.py", line 1582, in save_swp
    self.save_swp_to(swpname)
  File "/Users/ajda/orange/orange-canvas-core/orangecanvas/application/canvasmain.py", line 1598, in save_swp_to
    Pickler(f, document).dump(diff)
_pickle.PicklingError: Can't pickle : it's not the same object as Orange.data.filter.FilterContinuous
```

This should probably be fixed in both, Box Plot, but also canvas. I assume this is related to autosave, so errors should be caught and handled gracefully (I suppose).

**Comment by janezd** [comment]
> This should probably be fixed in both, Box Plot

During the big plague, the sheer number of deaths resulted in the doctrine of purgatory. It was obvious that most of the dead were not saintly enough to go to heaven, but inconcievable that they would all end in hell for eternity. Therefore the teaching of purgatory as a place of temporary redemption for one's sins, which did exist before, but only vaguely, was clarified by the church.

We of course know this caused problems down the road, with people encouraged to do or buy indulgences and so forth. But let us not judge them too harshly. There were two things that were unknown in those times. First, now, in the covid times, we know that the disease is caused by microorganisms and we know how it spreads, so we can fight it successfully even without cures or vaccines.

Second, we now know what the purgatory looks like and what people are doing there. They are fixing the box plot widget. Trust me on this. I spent the weekend on it, I still haven't finished, and I can imagine what these poor folks are going through.

**Comment by ajdapretnar** [comment]
Condolences.
