### ISSUE TITLE
Reload prompt on new workspace

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange-canvas-core#97]
Orange opens reload prompt ("Restore unsaved changes from crash?") on new workspace for no reason.

To reproduce:
1. Open Orange and place a widget on the canvas. Don't save anything.
2. Open a new workspace. It tries to reload a 'crashed' workflow, even where none exist.

Expected:
No prompt appears.

**Comment by janezd** [comment]
I would also be happy if there was an option -- could be hidden in an undocumented environment variable or wherever -- to disable this dialog altogether.

I usually test Orange by running it from shell, and I kill it with Ctrl-C instead of going through do-you-want-to-save-the-workflow dialog. But now this means that I always get this dialog when I reopen.

If nobody else has this problem, it's OK -- I'll just open Orange through a script that deletes the crashed workflow before starting. :)
